### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by DefinetlyNotAI** [Kuronons/FZ_graphics#4]
I am creating a HUGE flipper database, and would like to include your repo's files

You will be credited in the main ReadMe as the supplier and your special readme will also be provided

If you tell me NO, i will remove your repo from mine

Credits will give the link to this repo and your username

**Comment by DefinetlyNotAI** [comment]
https://github.com/DefinetlyNotAI/Full_Flipper_Database

**Comment by Kuronons** [comment]
Hey, well am not against the idea. Thing is that sometimes make lots of updates / changes... even on old anims releases and such. So you d have to be sure you get this updated...

Might be better to only have my repo as a simple link in yours...  especially when I use tons of links to share materials in my .md files.

Also, Awesome Flipper repo already exists and as he s back in the community, UberGuidoZ will most probably make major updates to it the upcoming times. 

 But I do understand your willing to provide THE database with your own view of sorting and such. 
 
 So no refusing on my end but yeah... think maybe twice on how you want to handle this.

**Comment by Kuronons** [comment]
Looking more in deep on how you you re sharing it, I find it a bit problematic.

For instance, you re sharing folders of anims I made with main readme in folder and subfolders... It s text I wrote using first person... *Here you can find what I did in blablabla*... and nothing will enlight the fact that is not your makings... 

...so yeah, link to repo, totally ok but including mine is yours as it doesn t feel right. I wouldn t do that with other makers for instance. Am sharing links to their own repo, adding lil comment, explanation, link to their profile but I believe it would not really be fair to just include their repo in mine.

**Comment by Kuronons** [comment]
And yeah by curiosity I looked at some dumps that are sharing some of my stuff... whatever how they did it, including, using sub-repo link, etc, it s always, always, always outdated. Which is not really great as, like every maker, I make sometimes fixes on stuff... and then on some DB /dumps, your broken stuff are still shared. ;/

Links are best imo. At least it directs the user to the latest stuff.

You could share readme.md but same thing, you d have to be sure those are updated on your repo as soon as they are edited in the original one.

Database is not a static thing... all the contrary. Needs loads of work to be maintened.

**Comment by DefinetlyNotAI** [comment]
can u advise me on the outdated files please?

**Comment by Kuronons** [comment]
> Hmm, thanks for you're great tips :) I appreciate it, I will definitely in the future update parts of it,
> 
> Though the idea of linking it in the repo sounds better in your case (as your case its still getting updates)
> 
> Can you tell me HOW to do that? Then ill remove the actual files, and just link it to your repo
> 
> Is this better? Thanks anyhow

Well you just edit what you did but editing the link of the repo so it goes to mine instead of the main Kuronons readme you have in your repo... Usually also, when crediting someone, you put the link of their GH's profile, not the repo's one.

![image](https://github.com/user-attachments/assets/c07bce2f-6db1-435c-aae8-c4d6e014aed0)

**Comment by Kuronons** [comment]
Also was thinking of something. As I am making my best to list everything that is related to Flipper's animations / graphic assets since now 2 years ago, such as custom anims makers, tutorials and tools, could be simpler to agree on some process to keep it fulfilled with latest finds.
If you find out some link, tool, tuto that is not listed on my readme, just tell me and I will edit it to add it.
This way, concerning this specific graphic field, people would have the means to find everything related on an unique readme.

I tend to think I linked 99% of what I found on GH for the anims/tools and same for tutos on YT. The last 1% was really not worth being included.

But there are probably some contents am not aware of.

**Comment by DefinetlyNotAI** [comment]
thx ;)

appreciate your wisdom and tips

I will fix your credits :)

Also ill make the dir link to your repo, so its always upto date ;)

**Comment by Kuronons** [comment]
YVW. Gathering info and sharing them in a user-friendly and understandable way is nice project. It s meant to evolve as you ll gather more and more info. But am sure you ll find ways to adjust.
Will take time and dedication. Best of luck anyway ! We keep in touch if ever you find things am not aware of ! O_oV

**Comment by DefinetlyNotAI** [comment]
Thx so much, i also appreciate yoyu giving it a star,

Thx for your help 💖
